# Generated by Django 3.0.8 on 2021-04-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190721_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='webpage',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
