# Generated by Django 3.0.8 on 2021-04-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menu_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(null=True, upload_to='package_image'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Package'),
        ),
    ]
